name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug Files
        run: ls -R
        working-directory: frontend

      - name: Clear Cypress Cache
        run: npx cypress cache clear
        working-directory: frontend

      - name: Install dependencies
        run: npm install
        working-directory: frontend

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          start: npm run test
          working-directory: frontend
