name: Test Automation

on:
  push:

  workflow_dispatch:

permissions:
  contents: write

jobs:
  test-automation:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    
    continue-on-error: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Start Server
        run: nohup npm run server &
        if: always()

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          working-directory: frontend
        if: always()
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: frontend/cypress/reports/
          publish_branch: gh-pages
          tag_name: ${{ steps.prepare_tag.outputs.DEPLOY_TAG_NAME }}
          tag_message: 'Deployment ${{ github.ref_name }}'
        if: always()

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: cypress-html-report
          path: frontend/cypress/reports/
        if: always()

      - name: Upload Cypress Screenshots as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend/cypress/screenshots/
        if: always()

      - name: Upload Cypress Videos as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/cypress/videos/
        if: always()